In [2]:
import numpy as np

## Defining Vectors and Matrices
Remember when we said that a vector is an array, and a matrix is a multi-dimensional array? The same concept applies to code. You just need to wrap your array in `np.array()`, which attaches all of the useful NumPy stuff to it.

In [3]:
# We define our matrices A and B
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12]])

# Let's print these values
print(f'A is {A}')
print(f'B is {B}')

A is [[1 2 3]
 [4 5 6]]
B is [[ 7  8  9]
 [10 11 12]]


Okay, now let's look at some properties of these values.

In [4]:
# shape: this returns the shape of the array.
# The return value of shape is of type tuple.

# A is a 2 x 3 matrix
print(f'The shape of A is {A.shape}')

# B is a 2 x 3 matrix
print(f'The shape of B is {B.shape}')

The shape of A is (2, 3)
The shape of B is (2, 3)


Let's say that we actually want the value at the first row in the first column of A to be 100. Well, NumPy uses dual indexing for its arrays

In [5]:
A[0,0] = 100
print(f"A is {A}")

A is [[100   2   3]
 [  4   5   6]]


Now, let's say that we actually want to replace the entire second row of B with the value -1. Well, NumPy supports slicing!

In [6]:
B[1, :] = -1
print(f"B is {B}")

B is [[ 7  8  9]
 [-1 -1 -1]]


Hmm, that doesn't look right. Rather, we have some very specific values in mind:

In [7]:
new_B_values = np.array([3.14, 42, 69])
print(f"Our new values are of type {new_B_values.dtype}")
print(f"B, however, is of type {B.dtype}")

Our new values are of type float64
B, however, is of type int64


Hmm, looks like there are issues with data types. We can't just add floats to an integer array, right?

In [8]:
B[1,:] = new_B_values
print(f"B is now of type {B.dtype}")
B

B is now of type int64


array([[ 7,  8,  9],
       [ 3, 42, 69]])

It converted our 3.14 to an integer automatically. That makes sense, I guess. Let's see how we can avoid this in future:

In [9]:
# First, convert B to a float array
B = B.astype('float64')

# Now, we can add floats in
B[1,:] = new_B_values

print(f"B is now {B} and of type {B.dtype}")

B is now [[ 7.    8.    9.  ]
 [ 3.14 42.   69.  ]] and of type float64


## Addition and Subtraction
Remember that two matrices can be added up if they are the same shape? Well, luckily for us, $\mathbf{A}$ and $\mathbf{B}$ are the same shape. Let's add them up

In [10]:
# Add A and B
sum_A_B = A + B
sum_A_B

array([[107.  ,  10.  ,  12.  ],
       [  7.14,  47.  ,  75.  ]])

In [11]:
# Subtract A and B
diff_A_B = A - B
diff_A_B

array([[ 93.  ,  -6.  ,  -6.  ],
       [  0.86, -37.  , -63.  ]])

## Scalar Multiplication
Scalar multiplication means that you are just multiplying a number with each element of the matrix.

In [12]:
# Let's define our scalar value (this is just a number)
scalar_value = 2

# Now, we multiply it with our matrix A
scalar_multiplication = scalar_value * A
scalar_multiplication

array([[200,   4,   6],
       [  8,  10,  12]])

## Dot Product
Okay, this has been fairly easy up until now. Let's try something more complicated: the dreaded dot product! Recall that we need two matrices, the first matrix must have the same number of columns as the second matrix has rows. Currently, we don't have that, so let's make one!

In [13]:
C = np.array([[1,2], [3, 4], [5,6]])

In [14]:
# Now, let's check that our shapes match up
print(f"The shape of A is {A.shape}")
print(f"The shape of C is {C.shape}")

The shape of A is (2, 3)
The shape of C is (3, 2)


Okay, great! This means that we will end up with a $2 \times 2$ matrix. But now how do we do that complicated formula? Well, NumPy has us sorted!

In [15]:
# We just use the np.dot method, which takes 2 arrays
dot_prod_A_C = np.dot(A,C)

# Let's see if we get the right shape
print(f"The dot product results in a shape of {dot_prod_A_C.shape}")

The dot product results in a shape of (2, 2)


## Using Data in NumPy
How do we convert all this to something useful? Let's say that we have an array X that contains our data for the X axis. How do we add the bias on?

In [16]:
X = np.array([2, 3, 4, 5])

print(f"X has shape {X.shape}")

X has shape (4,)


Hmm, this might be an issue. Firstly, we see that X has a shape of $4 \times 1$, which means it has 4 rows and 1 column. This makes it a row vector. And, on top of this, we still need to add the bias on. Let's tackle this one at a time. First, we begin by turning X into a column vector.

Wait, I remember something: the transpose! The transpose turns a matrix of shape $a \times b$ into a matrix of shape $b \times a$. This means that it will turn our "matrix" of shape $4 \times 1$ into a matrix of shape $1 \times 4$: this is a column vector!

Okay, first we need to tell NumPy that we want to look at X in two dimensions. To do this, we need to reshape it.

First, let's decide what the shape is. We want the same number of columns as X has rows. We also just want 1 row.

In [17]:
# Get the number of rows in X
x_rows = X.shape[0]

# We define a new shape. Remember, the shape is written in the form of a tuple
new_shape = (1, x_rows)

# Now, we reshape
X_reshaped = X.reshape(new_shape)

print(f"Our new shape is {X_reshaped.shape}")

Our new shape is (1, 4)


Excellent! Now for Step 2: adding the bias. We just need to create a new array with 2 rows and 4 columns. Then, we just need to fill the bottom row with 1s.

In [18]:
X_with_bias = np.empty(shape=(2, x_rows)) # 2 rows, 4 columns

# Fill the top row with the values of X
X_with_bias[0,:] = X

# Fill the bottom row with 1s
X_with_bias[1,:] = 1

# Now, let's see our work
print(X_with_bias)

[[2. 3. 4. 5.]
 [1. 1. 1. 1.]]
